// react_users/frontend/src/components/Menu.jsx
import { Link } from "react-router-dom";

function Menu() {
  return (
    <div className="navbar bg-lime-300 shadow-sm">
      <div className="flex-1">
        <Link to="/" className="btn btn-ghost text-xl">Main</Link>
      </div>
      <div className="flex-none">
        <ul className="menu menu-horizontal px-1">
          <li>
            <Link to="/login">Login</Link>
          </li>
           <li>
            <Link to="/register">Register</Link>
          </li>                    
        </ul>
      </div>
    </div>
  );
}

export default Menu;

// vue_alapok/src/components/Menu.vue
<script setup>
import {RouterLink} from "vue-router";
</script>

<template>
    <div class="navbar bg-sky-300 shadow-sm">
        <div class="flex-1">
            <RouterLink to="/" class="btn btn-ghost text-xl">Főoldal</RouterLink>
        </div>
        <div class="flex-none">
            <ul class="menu menu-horizontal px-1">
                <li><RouterLink to="/posts">Posztok</RouterLink></li>               
            </ul>
        </div>
    </div>

</template>
