// vue_alapok/src/components/Post.vue
<script setup>
defineProps({post:Object})
</script>

<template>
    <div class="m-5 card w-96 bg-base-100 card-md shadow-sm">
        <div class="card-body">
            <h2 class="card-title">{{post.title}}</h2>
            <p>{{ post.body }}</p>
            <div class="justify-end card-actions">
                
            </div>
        </div>
    </div>
</template>

// react_tailwind/src/components/Post.jsx
function Post({ post }) {
  return (
    <div className="m-5 card card-border bg-amber-200 w-96">
      <div className="card-body">
        <h2 className="card-title">UserId:{post.userId}</h2>
        <p>Post Id:{post.id}</p>
        <p>{post.title}</p>
        <p>{post.body}</p>
      </div>
    </div>
  );
}

export default Post;
